<a href="https://colab.research.google.com/github/elnursahbalayev/UTP_Data_Analytics/blob/main/00_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")


Hello World


In [ ]:
num1 = input('Enter first number: ') 
num2 = input('Enter second number: ') 


Enter first number: 2
Enter second number: 3


In [ ]:
# Add two numbers
sum = float(num1) + float(num2)
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

The sum of 2 and 3 is 5.0


In [ ]:
# Multiply two numbers
prod = float(num1) * float(num2) 


In [ ]:
print('The product of {0} and {1} is {2}'.format(num1, num2, prod))


The product of 2 and 3 is 6.0


In [ ]:
#define a function that takes 2 nunbers as input and their product as output 
def multiply(x,y):   
  return x*y


In [ ]:
#call the function for 5 and 3
multiply(5,3)

15

In [ ]:
num = input('Enter first number: ') 
x=float(num)
if x > 0:    print(x, "is a positive number.")

elif x < 0:    print(x, "is a negative number.")

else:  print("you entered zero.") 

Enter first number: 3.4
3.4 is a positive number.


In [ ]:
for x in range (7):    print (x)

0
1
2
3
4
5
6


In [ ]:
#while loop
i = 1
while i < 7:
  print(i)
  i += 1


1
2
3
4
5
6


In [ ]:
#while if loop
i = 1
while i < 7:
  print(i)
  if i == 3:
    break
  i += 1


1
2
3


In [ ]:
#import NumPy
import numpy as np
a = np.array([1,2,3,4,5])
print('a:',a)


a: [1 2 3 4 5]


In [ ]:
#Know the type of an array
print('type of a:',type(a))


type of a: <class 'numpy.ndarray'>


In [ ]:
print('a = ',a)
a[0] = 10
print('a = ',a)
a[2] = 13.6
print('a =', a)


a =  [1 2 3 4 5]
a =  [10  2  3  4  5]
a = [10  2 13  4  5]


In [ ]:
# to get the shape of an array
print("the shape of a is") 
a.shape

the shape of a is


(5,)

In [ ]:
b=5
add = a + b
multip = a * b
divis = a / b
pwr = b**a

print('a:', a)
print('b:',b)
print('add:', add)
print('multiply:', multip)
print ('division:',divis)
print ('power:',pwr)

a: [10  2 13  4  5]
b: 5
add: [15  7 18  9 10]
multiply: [50 10 65 20 25]
division: [2.  0.4 2.6 0.8 1. ]
power: [   9765625         25 1220703125        625       3125]


In [ ]:
# Multi-Dimensional Array
d = np.array([[0, 1, 3, 5, 7], [10, 11, 12, 13, 14], [20, 22, 24, 25, 27]])
print(d)
print('shape:',d.shape)
print('size:',d.size)


[[ 0  1  3  5  7]
 [10 11 12 13 14]
 [20 22 24 25 27]]
shape: (3, 5)
size: 15


In [ ]:
# var[lower:upper:step] @ [lower:upper:step]
a = np.array([1,5,7,9,12])
print('a = ',a)


a =  [ 1  5  7  9 12]


In [ ]:
#a[1:3] gives the values at indices 1 to 3 (excluded)
print('a[1:3] =',a[1:3])


a[1:3] = [5 7]


In [ ]:
#a[1:4] gives the values at indices 1 to 3 (excluded)
print('a[1:4] =',a[1:4])

a[1:4] = [5 7 9]


In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
# new array object but not new number (memory buffer shared!)
b = a[:2]    


In [ ]:
print('a:',a)
print('b:',b)
b[0] = -5
print('b:',b)


a: [1 2 3 4 5]
b: [1 2]
b: [-5  2]


In [ ]:
# create an array with numbers from 0 to 50 (excluded) with a gap of 5
a = np.arange(0,50,5)


In [ ]:
# create an array of indices
idx = [1,2,-4]


In [ ]:
# extract an array corresponding to the given indices
y = a[idx]
print('a:',a)
print('y:',y)


a: [ 0  5 10 15 20 25 30 35 40 45]
y: [ 5 10 30]


In [ ]:
# indexing with BOOLEANS
mask = np.array([0,1,1,0,0,1,1,1,0,0], dtype= bool)
y = a[mask]
print('a:',a)
print('y:',y)


a: [ 0  5 10 15 20 25 30 35 40 45]
y: [ 5 10 25 30 35]
